version: "3.8"

networks:
  chat:

services:
  chat_app:
    networks:
      - chat
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    image: 'chat_app:latest'
    build:
      context: .
    container_name: chat_app
    ports:
      - "8085:8085"
    env_file:
      - .env
    restart: always
