server:
  port: 8086
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true
keycloak:
  authServerUrl: http://host.docker.internal:8484/auth
  realm: chat
  resource: chat-app-be
  ssl-required: external
  credentials:
    secret: 7xggFgU1lp0H37PNkPvL3Ycf5iE3qepY